---
yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint"
rules:
  anchors: enable
  braces:
    max-spaces-inside: 1
  brackets: enable
  colons: enable
  commas: enable
  comments:
    level: warning
    min-spaces-from-content: 1
  comments-indentation: false
  document-end: disable
  document-start: enable
  empty-lines:
    max-end: 1
  empty-values: disable
  float-values: disable
  hyphens:
    max-spaces-after: 1
  indentation: enable
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values:
    forbid-explicit-octal: true
    forbid-implicit-octal: true
  quoted-strings: disable
  trailing-spaces: enable
  truthy:
    level: warning
    allowed-values:
      - 'true'
      - 'false'
