---
- name: Sample Ansible Playbook
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create a local file
      file:
        path: "/tmp/testfile"
        state: touch