---
name: pre-commit-checks
run-name: "${{ github.actor }} has triggered the ${{ github.workflow }} workflow"
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  workflow_call:
    inputs:
      python_version:
        description: 'Python version to use'
        required: false
        default: '3.13.0'
        type: string
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}  # This is the concurrency group name and should be unique per pull request
  cancel-in-progress: ${{ !contains(github.ref, 'release/')}}  # Cancel previous runs if a new run is triggered on a non-release branch
env:
  PYTHON_VERSION: ${{ github.head_ref && '3.13.0' || github.event.inputs.python_version }}
permissions:
  contents: read
jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install python dependencies
        run: |-
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            python -m pip install pre-commit
          fi
      - name: Run pre-commit
        run: |-
          pre-commit run --all-files --verbose
